### ISSUE TITLE
要是在命令行上面带入数据库相关参数可能会更好用

### ISSUE THREAD

**Issue by hadesfeng** [smartyhero/schema-diff#1]
其实 Vitess官方的那一篇博客我先前也看过了：
https://vitess.io/blog/2023-04-24-schemadiff/ 

作者你要是这个工具你新增在命令行上可以带入数据库相关参数（ip、端口、账号密码等等），这样的话可能会更好用！

**Comment by smartyhero** [comment]
接下来支持一下, 本来是觉得命令行参数有很多, 指定起来会比较麻烦, 所以只使用了配置文件

**Comment by smartyhero** [comment]
已经加上啦: https://github.com/smartyhero/schema-diff/releases/tag/v0.0.3
